// Dictionary to determine political stance of news sources
module.exports = {
  'Sky News' : 5,
  'BBC News' : 5,
  'The Guardian' : 1,
  'The Independent' : 1,
  'Metro.co.uk' : 1,
  'Telegraph.co.uk' : 10,
  'The Telegraph' : 10,
  'The Times' : 10,
  'The Sun' : 10,
  'Daily Mail' : 10,
  'Daily Star' : 5,
  'Morning Star Online' : 1,
  'Evening Standard' : 10,
  'City A.M.' : 10,
  'ITV News' : 10,
  'Channel 4 News' : 1,
  'Express' : 10,
  'Mirror Online' : 1,
  'Financial Times' : 5,
  'The Irish Times' : 1,
  'Irish Examiner' : 1,
  'expressandstar.com' : 1,
  'Daily Express' : 10,
  'Washington Post' : 1,
  'CNBC' : 1,
  'Reuters UK' : 5,
  'Reuters' : 5,
  'The London Economic' : 5,
  'New Statesman' : 1,
  'EUobserver' : 1,
  'The New European' : 1,
  'Aljazeera.com' : 1,
  'Bloomberg' : 5,
  'LBC' : 1,
  'Arab News' : 10,
  'Hindustan Times' : 5,
  'Times of Malta' : 10,
  'News24' : 5,
  'Wales Online' : 5,
  'iNews' : 1,
  'Kent Live' : 11,
  'Bournemouth Echo' : 11,
  'Yorkshire Post' : 11,
  'Dorset Echo' : 11,
  'Liverpool Echo' : 11,
  'Spectator.co.uk' : 10,
  'Plymouth Live' : 11,
  'Teesside Live' : 11,
  'Cambridgeshire Live' : 11,
  'Manchester Evening News' : 11,
  'Essex Live' : 11,
  'Leeds Live' : 11,
  'Grimsby Live' : 11,
  'MSN UK' : 11,
  'CGTN' : 1,
  'Sputnik International' : 10,
  'Daily Record' : 11,
  'Chronicle Live' : 11,
  'The Economist': 5,
  'Private Eye': 5,
  'NBC' : 5,
  'Fox News' : 10
};